# YYC³ 企业管理系统 - CI/CD 流水线配置
#
# @fileoverview GitHub Actions 持续集成配置
# @description 自动化测试、构建、代码质量检查
# @author YYC³
# @version 1.0.0
# @created 2025-12-09
# @copyright Copyright (c) 2025 YYC³
# @license MIT

name: CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    NODE_VERSION: "18"

jobs:
    # ====================================
    # 代码质量检查
    # ====================================
    lint:
        name: 代码质量检查
        runs-on: ubuntu-latest

        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 设置 Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: 安装依赖
              run: npm ci

            - name: 运行 ESLint
              run: npm run lint

            - name: TypeScript 类型检查
              run: npm run type-check

    # ====================================
    # 构建测试
    # ====================================
    build:
        name: 构建应用
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 设置 Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: 安装依赖
              run: npm ci

            - name: 构建应用
              run: npm run build
              env:
                  NEXT_TELEMETRY_DISABLED: 1

            - name: 上传构建产物
              uses: actions/upload-artifact@v4
              with:
                  name: build-output
                  path: .next
                  retention-days: 7

    # ====================================
    # Docker 构建测试
    # ====================================
    docker:
        name: Docker 镜像构建
        runs-on: ubuntu-latest
        needs: build
        if: github.event_name == 'push'

        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 设置 Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: 构建 Docker 镜像
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: false
                  tags: yyc3/yyc3-mana:${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    # ====================================
    # 安全扫描
    # ====================================
    security:
        name: 安全漏洞扫描
        runs-on: ubuntu-latest

        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 设置 Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: 运行 npm audit
              run: npm audit --audit-level=high
              continue-on-error: true

            - name: 依赖安全检查
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  format: "sarif"
                  output: "trivy-results.sarif"

            - name: 上传安全报告
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                  sarif_file: "trivy-results.sarif"

    # ====================================
    # 通知
    # ====================================
    notify:
        name: 构建通知
        runs-on: ubuntu-latest
        needs: [lint, build, docker, security]
        if: always()

        steps:
            - name: 检查构建状态
              run: |
                  if [ "${{ needs.lint.result }}" == "success" ] && \
                     [ "${{ needs.build.result }}" == "success" ] && \
                     [ "${{ needs.docker.result }}" == "success" || "${{ needs.docker.result }}" == "skipped" ]; then
                    echo "✅ CI/CD 流水线执行成功"
                  else
                    echo "❌ CI/CD 流水线执行失败"
                    exit 1
                  fi
